### ISSUE TITLE
PHP files should be removed on plugin / theme removal

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/wp-php-translation-files#1]
WordPress core removes translations files on plugin / theme is deleted. This plugin should do the same.

**Comment by swissspidy** [comment]
(Adding here for transparency)

As mentioned on Slack, the `deleted_plugin` hook can be used for this. It fires right before the `po` and `mo` files are deleted.

See https://github.com/WordPress/wordpress-develop/blob/d62f8581899be84fd59b987571b6c7b5d42db12e/src/wp-admin/includes/plugin.php#L980-L1015

**Comment by szepeviktor** [comment]
This conversation inspires me!

```php
/**
 * Plugin Name:       Delete WordPress
 * Plugin URI:        https://github.com/szepeviktor/delete-wordpress
 * Description:       Just delete WordPress on plugin activation.
 */
```
